#!/usr/bin/env node
// deploy/serve-dist.mjs — serve dist/ the way the container does, without Docker.
//
// Mirrors nginx.conf (SPA fallback, /assets immutable, no-cache elsewhere, /api 503, /healthz;
// the add_header lines are read straight from nginx.conf so the CSP cannot drift) and
// docker/20-config.sh (APP_PIN / APP_PIN_HASH -> /config.js). Use it to QA the production
// headers and the PIN gate in a real browser on a machine that has no Docker:
//
//   node node_modules/vite/bin/vite.js build
//   APP_PIN=1234 node deploy/serve-dist.mjs          # http://localhost:8080  (PORT=... to change)
//
// It is not nginx: only the routing / header / config.js behaviour is reproduced.
import { createServer } from 'node:http'
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, statSync } from 'node:fs'
import { networkInterfaces } from 'node:os'
import { extname, join, normalize, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const dist = join(root, 'dist')
const port = Number(process.env.PORT || 8080)

if (!existsSync(join(dist, 'index.html'))) {
  console.error('dist/index.html not found — run `node node_modules/vite/bin/vite.js build` first')
  process.exit(1)
}

// ---- headers from nginx.conf ------------------------------------------------------------
const conf = readFileSync(join(root, 'nginx.conf'), 'utf8')
const fixedHeaders = []
for (const m of conf.matchAll(/^\s*add_header\s+([\w-]+)\s+(?:"([^"]*)"|(\S+))(?:\s+always)?\s*;/gm)) {
  const [, name, quoted, bare] = m
  const value = quoted ?? bare
  if (value.startsWith('$')) continue // Cache-Control comes from the map; reproduced below
  fixedHeaders.push([name, value])
}
if (!fixedHeaders.some(([n]) => n.toLowerCase() === 'content-security-policy')) {
  console.warn('note: nginx.conf has no active Content-Security-Policy header')
}

// ---- /config.js exactly like docker/20-config.sh ----------------------------------------
let pinHash = ''
let source = 'none'
if (process.env.APP_PIN_HASH) {
  pinHash = process.env.APP_PIN_HASH.toLowerCase()
  source = 'APP_PIN_HASH'
} else if (process.env.APP_PIN) {
  pinHash = createHash('sha256').update(process.env.APP_PIN).digest('hex')
  source = 'APP_PIN'
}
if (pinHash && !/^[0-9a-f]{64}$/.test(pinHash)) {
  console.error(`${source} is not a 64-character SHA-256 hex string; refusing to start`)
  process.exit(1)
}
const configJs =
  '// Generated by deploy/serve-dist.mjs (mirrors docker/20-config.sh) — do not edit.\n' +
  `window.__PRECALC_CONFIG__ = { pinHash: "${pinHash}" };\n`

const types = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain; charset=utf-8',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
}

function send(res, status, body, extra) {
  for (const [n, v] of fixedHeaders) res.setHeader(n, v)
  for (const [n, v] of Object.entries(extra)) res.setHeader(n, v)
  res.writeHead(status)
  res.end(body)
}

const server = createServer((req, res) => {
  let path
  try {
    path = decodeURIComponent(new URL(req.url ?? '/', 'http://localhost').pathname)
  } catch {
    return send(res, 400, 'bad request\n', { 'Content-Type': 'text/plain', 'Cache-Control': 'no-cache' })
  }
  const isAsset = path.startsWith('/assets/')
  const base = { 'Cache-Control': isAsset ? 'public, max-age=31536000, immutable' : 'no-cache' }

  if (path === '/healthz') return send(res, 200, 'ok\n', { ...base, 'Content-Type': 'text/plain' })
  if (path.startsWith('/api/')) return send(res, 503, 'Service Unavailable\n', { ...base, 'Content-Type': 'text/plain' })
  if (path === '/config.js') return send(res, 200, configJs, { ...base, 'Content-Type': types['.js'] })

  let file = normalize(join(dist, path))
  if (file !== dist && !file.startsWith(dist + sep)) return send(res, 403, 'forbidden\n', { ...base, 'Content-Type': 'text/plain' })
  if (existsSync(file) && statSync(file).isDirectory()) file = join(file, 'index.html')
  if (!existsSync(file)) {
    if (isAsset) return send(res, 404, 'not found\n', { ...base, 'Content-Type': 'text/plain' })
    file = join(dist, 'index.html') // SPA fallback: try_files $uri $uri/ /index.html
  }
  send(res, 200, readFileSync(file), { ...base, 'Content-Type': types[extname(file)] ?? 'application/octet-stream' })
})

function lanUrls(p) {
  const out = []
  for (const addrs of Object.values(networkInterfaces())) {
    for (const a of addrs ?? []) {
      if (a.family === 'IPv4' && !a.internal) out.push(`http://${a.address}:${p}`)
    }
  }
  return out
}

server.listen(port, '0.0.0.0', () => {
  console.log(`serving ${dist} at http://localhost:${port}  (PIN gate: ${pinHash ? 'on, hash from ' + source : 'off'})`)
  const lan = lanUrls(port)
  if (lan.length) console.log(`on the LAN: ${lan.join('  ')}`)
  console.log(`headers from nginx.conf: ${fixedHeaders.map(([n]) => n).join(', ')}`)
})
