/**
 * The coaching library: one entry per ErrorPatternId (title, lesson, wrong → right example).
 * Seeded by the ENGINE agent from research/error-patterns-and-hints.md; the MATCHERS agent owns
 * refinements. Voice: coach, names the property, shows the concrete number.
 */
import type { ErrorPatternId, ErrorPatternInfo, PatternHit } from '@/shared/types'

export const ERROR_PATTERNS: Record<ErrorPatternId, ErrorPatternInfo> = {
  // --- final-answer / notation (notation layer) ---
  backwards_interval: {
    id: 'backwards_interval',
    title: 'Intervals read left to right',
    lesson: 'Intervals read left → right on the number line; −∞ always leads and gets a (.',
    example: '[3, −∞) → (−∞, 3]',
  },
  dropped_union: {
    id: 'dropped_union',
    title: 'Two pieces need a ∪',
    lesson: 'Two separate pieces need ∪ between them — one interval can\'t have a gap.',
    example: '(−∞, −2] (5, ∞) → (−∞, −2] ∪ (5, ∞)',
  },
  bracket_point: {
    id: 'bracket_point',
    title: 'A single number is a set',
    lesson: 'A single number is a set of one element: {3}. Brackets need two endpoints.',
    example: '[3] → {3}',
  },
  set_interval_mismatch: {
    id: 'set_interval_mismatch',
    title: 'Your two answers disagree',
    lesson: 'Your interval and your set describe different numbers — one includes a value the other leaves out.',
    example: '(−∞, 2) vs {x | x ≤ 2}: x = 2 is in one but not the other',
  },
  wrong_side: {
    id: 'wrong_side',
    title: 'Shaded the wrong side',
    lesson: 'x > −2 is to the RIGHT of −2. Read the symbol as an arrow from x.',
    example: 'x > −2 → (−2, ∞), not (−∞, −2)',
  },
  endpoint_type: {
    id: 'endpoint_type',
    title: 'Bracket or parenthesis?',
    lesson: '≤ includes the endpoint → bracket; < excludes it → parenthesis.',
    example: 'x ≤ 2 → (−∞, 2], not (−∞, 2)',
  },
  infinity_bracket: {
    id: 'infinity_bracket',
    title: 'Infinity is never reached',
    lesson: '∞ is not a number you can land on, so it always gets a parenthesis.',
    example: '[3, ∞] → [3, ∞)',
  },
  empty_interval: {
    id: 'empty_interval',
    title: 'That interval is empty',
    lesson: 'An interval whose left end is past its right end contains nothing. Check which way the symbol points.',
    example: '(5, 2) → (2, 5)',
  },
  // --- inequality direction (engine) ---
  no_sign_flip: {
    id: 'no_sign_flip',
    title: 'Dividing by a negative flips the symbol',
    lesson: 'Multiplying or dividing both sides by a NEGATIVE turns the symbol around; adding or subtracting never does.',
    example: '−14 ≤ −14x → x ≥ 1 ✗ → x ≤ 1',
  },
  flip_on_positive: {
    id: 'flip_on_positive',
    title: 'Positive multiplier — the symbol stays',
    lesson: 'You flipped, but you divided by a POSITIVE number. Only a negative multiplier turns the symbol around.',
    example: '3x < 6 → x > 2 ✗ → x < 2',
  },
  flip_on_add: {
    id: 'flip_on_add',
    title: 'Adding never flips',
    lesson: 'Adding or subtracting on both sides never flips the symbol — only a negative multiplier does.',
    example: 'x + 2 < 5 → x > 3 ✗ → x < 3',
  },
  swap_sides_no_reverse: {
    id: 'swap_sides_no_reverse',
    title: 'Swapping sides reverses the symbol',
    lesson: 'Reading an inequality backwards reverses the symbol: 3 < x is the same as x > 3.',
    example: '3 < x → x < 3 ✗ → x > 3',
  },
  nonconstant_multiplier_inequality: {
    id: 'nonconstant_multiplier_inequality',
    title: 'That multiplier changes sign',
    lesson: 'Multiplying an inequality by an expression whose sign depends on x is not a single legal move — for some x it flips, for others it doesn\'t.',
    example: '1/x < 2 → 1 < 2x ✗ (fails at x = −1)',
  },
  // --- algebra steps (engine) ---
  cbrt_sign_dropped: {
    id: 'cbrt_sign_dropped',
    title: 'Cube roots keep the sign',
    lesson: 'A cube root keeps the sign: ∛(−8) = −2, so ∛(−u) = −∛u. You may pull the minus out, never drop it.',
    example: 'cbrt(−x) → cbrt(x) ✗ → −cbrt(x)',
  },
  dropped_pm: {
    id: 'dropped_pm',
    title: 'Even roots give two answers',
    lesson: 'Even roots give two answers: if u² = 9 then u = ±3. Write both, or say why one is excluded.',
    example: 'x² = 9 → x = 3 ✗ → x = ±3',
  },
  minus_teleport: {
    id: 'minus_teleport',
    title: 'The minus jumped out of the denominator',
    lesson: 'A minus in front of a fraction negates the WHOLE denominator: 1/(−x+2) = −1/(x−2).',
    example: '1/(−x+2) → −1/(x+2) ✗ → −1/(x−2)',
  },
  partial_distribute: {
    id: 'partial_distribute',
    title: 'Distribution missed a term',
    lesson: 'Distribute to EVERY term inside the parentheses: x(y+2) = xy + 2x.',
    example: 'x(y+2) → xy + 2 ✗ → xy + 2x',
  },
  negative_not_distributed: {
    id: 'negative_not_distributed',
    title: 'The minus is part of the multiplier',
    lesson: 'The minus sign is part of the multiplier, so it reaches every term: −2(x−3) = −2x + 6.',
    example: '−2(x−3) → −2x − 6 ✗ → −2x + 6',
  },
  const_into_radical: {
    id: 'const_into_radical',
    title: 'The constant is outside the root',
    lesson: 'cbrt(u) − 1 is not cbrt(u − 1). Undo the −1 first (add 1 to both sides), then deal with the root. Same trap on the calculator: close ³√( ) before the −1.',
    example: 'cbrt(7x+3) − 1 → cbrt(7x+2) ✗',
  },
  op_on_one_term: {
    id: 'op_on_one_term',
    title: 'The operation applies to the whole side',
    lesson: 'Cubing (or any both-sides move) applies to the whole side, not one term. Isolate the radical first, then cube everything.',
    example: 'y = cbrt(7x+3) − 1 → y³ = 7x+3 − 1 ✗',
  },
  reciprocal_coeff: {
    id: 'reciprocal_coeff',
    title: 'Undo a coefficient with its reciprocal',
    lesson: 'A coefficient is multiplication, so it\'s undone by multiplying by the reciprocal — on EVERY term of the other side.',
    example: '(3/5)y = x − 2 → y = (5/3)x − 2 ✗ → y = (5/3)(x − 2)',
  },
  term_across_sign: {
    id: 'term_across_sign',
    title: 'Moving a term changes its sign',
    lesson: 'Moving a term across the = or inequality sign means subtracting it from both sides, so its sign changes.',
    example: 'x + 3 = 7 → x = 7 + 3 ✗ → x = 7 − 3',
  },
  power_over_sum: {
    id: 'power_over_sum',
    title: 'Powers don\'t distribute over +',
    lesson: 'Powers and roots distribute over multiplication, never over addition: (xy)² = x²y² but (x+y)² ≠ x²+y².',
    example: '(x+1)³ → x³ + 1 ✗',
  },
  split_denominator: {
    id: 'split_denominator',
    title: 'You can\'t split a denominator',
    lesson: 'You can split a numerator sum, not a denominator sum: (a+b)/c = a/c + b/c, but c/(a+b) stays.',
    example: '3/(x+2) → 3/x + 3/2 ✗',
  },
  cancel_term: {
    id: 'cancel_term',
    title: 'Only factors cancel',
    lesson: 'Only common FACTORS cancel; every term of the numerator gets divided.',
    example: '(2x+4)/2 → x + 4 ✗ → x + 2',
  },
  add_denominators: {
    id: 'add_denominators',
    title: 'Fractions need a common denominator',
    lesson: 'Fractions need a common denominator; 1/2 + 1/2 is not 2/4.',
    example: '1/x + 1/2 → 2/(x+2) ✗',
  },
  sqrt_square_abs: {
    id: 'sqrt_square_abs',
    title: '√(u²) is |u|',
    lesson: '√(u²) is |u|; it is never negative.',
    example: 'sqrt((x−1)²) → x − 1 ✗ → |x − 1|',
  },
  divide_by_variable: {
    id: 'divide_by_variable',
    title: 'Dividing by a variable can lose a solution',
    lesson: 'You divided by an expression that can be 0 — the solution where it IS 0 vanished. Factor instead: x(x − 3) = 0.',
    example: 'x² = 3x → x = 3 ✗ (lost x = 0)',
  },
  squaring_caveat: {
    id: 'squaring_caveat',
    title: 'Legal, but check for extra answers',
    lesson: 'Squaring (or multiplying by an expression with the variable) can create extra answers — check each answer in the original at the end.',
    example: '√x = −3 → x = 9 ⚠ (9 fails the original)',
  },
  combine_unlike: {
    id: 'combine_unlike',
    title: 'Only like terms combine',
    lesson: 'Only like terms combine: 2x + 3 stays 2x + 3.',
    example: '2x + 3 → 5x ✗',
  },
  neg_power_sign: {
    id: 'neg_power_sign',
    title: '(−x)ⁿ and −xⁿ differ',
    lesson: '(−x)² = x², but −x² is the negative of x²; odd powers keep the minus.',
    example: '(−x)² → −x² ✗',
  },
  substitution_error: {
    id: 'substitution_error',
    title: 'Replace EVERY x with (−x)',
    lesson: 'Replace EVERY x with (−x), keep the parentheses, then simplify each power.',
    example: 'x³ + x → −x³ + x ✗ → −x³ − x',
  },
  reciprocal_as_inverse: {
    id: 'reciprocal_as_inverse',
    title: 'f⁻¹ is not 1/f',
    lesson: 'f⁻¹ undoes f; it is not 1/f. Check: f(f⁻¹(k)) should return k.',
    example: 'f(x) = 2x+1 → f⁻¹(x) = 1/(2x+1) ✗',
  },
  swap_misname: {
    id: 'swap_misname',
    title: 'Swap BOTH letters',
    lesson: 'To find an inverse, every x becomes y AND every y becomes x. Renaming only one letter gives a different equation.',
    example: 'y = (x+1)³ → x = (x+1)³ ✗ → x = (y+1)³',
  },
  // --- difference quotient (engine/diffQuotient.ts) ---
  dq_fx_plus_h: {
    id: 'dq_fx_plus_h',
    title: 'f(x + h) means “put x + h into f”',
    lesson: 'f(x + h) is not f(x) + h. The input changes, so every x in the formula becomes (x + h); adding h to the output would just lift the graph up.',
    example: 'f(x) = x^2 + 1: f(x + h) → x^2 + 1 + h ✗ → (x + h)^2 + 1',
  },
  dq_fx_plus_fh: {
    id: 'dq_fx_plus_fh',
    title: 'A function doesn’t split over +',
    lesson: 'f(x + h) is not f(x) + f(h): you can’t feed the x and the h in separately. Put the whole (x + h) wherever x was.',
    example: 'f(x) = 3x − 2: f(x + h) → (3x − 2) + (3h − 2) ✗ → 3(x + h) − 2',
  },
  dq_partial_sub: {
    id: 'dq_partial_sub',
    title: 'Replace EVERY x with (x + h)',
    lesson: 'Every x in the formula becomes (x + h), not just the first one. Go through f term by term and swap each x.',
    example: '3x^2 + 2x − 1 → 3(x + h)^2 + 2x − 1 ✗ → 3(x + h)^2 + 2(x + h) − 1',
  },
  dq_partial_cancel: {
    id: 'dq_partial_cancel',
    title: 'Every term gives up one h',
    lesson: 'Dividing the numerator by h divides EVERY term, so each term loses exactly one h. Factoring h out first keeps it honest: h(2x + h + 3)/h.',
    example: '(2xh + h^2 + 3h)/h → 2x + h^2 + 3 ✗ → 2x + h + 3',
  },
  dq_forgot_divide: {
    id: 'dq_forgot_divide',
    title: 'Don’t lose the h underneath',
    lesson: 'The difference quotient is the change in f DIVIDED by h. You have the top, f(x + h) − f(x); keep the /h and let it cancel.',
    example: '(5x + 5h − 2 − (5x − 2))/h → 5h ✗ → 5',
  },
  dq_set_h_zero: {
    id: 'dq_set_h_zero',
    title: 'Keep the h — for now',
    lesson: 'Letting h shrink to 0 is the NEXT big idea (the derivative), so good instinct! But the difference quotient keeps its h: it is the slope of a secant line for any h ≠ 0.',
    example: '(6xh + 3h^2 + 2h)/h → 6x + 2 ✗ → 6x + 3h + 2',
  },
  // --- significant figures (engine/sigfigs; chemistry) ---
  sf_leading_zeros: {
    id: 'sf_leading_zeros',
    title: 'Leading zeros never count',
    lesson: 'Zeros in front of the first nonzero digit only place the decimal point. Start counting at the first nonzero digit.',
    example: '0.00450 → 6 figures ✗ → 3 figures (4, 5, 0)',
  },
  sf_trailing_zeros_decimal: {
    id: 'sf_trailing_zeros_decimal',
    title: 'Zeros after a decimal point were measured',
    lesson: 'When a decimal point is written, the zeros at the end are significant: someone measured them. Otherwise nobody would write them.',
    example: '100.0 → 1 figure ✗ → 4 figures',
  },
  sf_placeholder_zeros: {
    id: 'sf_placeholder_zeros',
    title: 'No decimal point, so those zeros are placeholders',
    lesson: 'In a whole number written without a decimal point, the zeros at the end only hold the place. A written point (1200.) is what makes them count.',
    example: '1200 → 4 figures ✗ → 2 figures; 1200. → 4 figures',
  },
  sf_captive_zero: {
    id: 'sf_captive_zero',
    title: 'Zeros in the middle count',
    lesson: 'A zero sandwiched between significant digits is significant too. It was read off the instrument like its neighbors.',
    example: '5002 → 2 figures ✗ → 4 figures',
  },
  sf_addsub_rule_on_muldiv: {
    id: 'sf_addsub_rule_on_muldiv',
    title: '× and ÷ go by significant figures',
    lesson: 'Lining up decimal places is the rule for + and −. For × and ÷, count significant figures and keep the FEWEST.',
    example: '2.0 × 11.31 = 22.62 → 22.6 ✗ → 23 (two figures, like 2.0)',
  },
  sf_muldiv_rule_on_addsub: {
    id: 'sf_muldiv_rule_on_addsub',
    title: '+ and − go by decimal places',
    lesson: 'Counting significant figures is the rule for × and ÷. For + and −, line up the places and round to the LEAST precise one.',
    example: '104.52 + 3.1 = 107.62 → 110 ✗ → 107.6 (tenths, like 3.1)',
  },
  sf_most_precise: {
    id: 'sf_most_precise',
    title: 'The weakest measurement sets the limit',
    lesson: 'An answer can only be as good as its least precise measurement, so match the FEWEST figures (or the least precise place), not the most.',
    example: '2.4 × 3.421 = 8.2104 → 8.210 ✗ → 8.2',
  },
  sf_unrounded: {
    id: 'sf_unrounded',
    title: 'The calculator shows more than you measured',
    lesson: 'A calculator prints every digit it can; most of them are noise. Round to what the measurements support.',
    example: '12.50 ÷ 4.1 → 3.04878 ✗ → 3.0',
  },
  sf_truncated: {
    id: 'sf_truncated',
    title: 'Round, don’t chop',
    lesson: 'Look at the first digit you drop: 5 or more and the last kept digit goes up by one; less than 5 and it stays.',
    example: '0.004567 to 2 figures → 0.0045 ✗ → 0.0046',
  },
  sf_places_not_figures: {
    id: 'sf_places_not_figures',
    title: 'Significant figures aren’t decimal places',
    lesson: 'Decimal places count from the point. Significant figures count from the first nonzero digit, wherever the point is.',
    example: '0.004567 to 2 figures → 0.00 ✗ → 0.0046',
  },
  sf_dropped_zero: {
    id: 'sf_dropped_zero',
    title: 'Keep the zero that shows your precision',
    lesson: 'A trailing zero after the decimal point is significant. Dropping it says the answer is less precise than it really is.',
    example: '12.50 ÷ 4.1 → 3 ✗ → 3.0 (two figures)',
  },
  sf_extra_zeros: {
    id: 'sf_extra_zeros',
    title: 'Extra zeros claim extra precision',
    lesson: 'Every zero written after the decimal point says "I measured this". Stop where the limiting measurement stops.',
    example: '12.11 + 18.0 + 1.013 → 31.10 ✗ → 31.1 (tenths, like 18.0)',
  },
  sf_ambiguous_zeros: {
    id: 'sf_ambiguous_zeros',
    title: 'Those zeros read as placeholders',
    lesson: 'A whole number with no decimal point hides whether its zeros were measured. Scientific notation shows exactly the figures you mean.',
    example: '1999 to 2 figures → 2000 ✗ (reads as 1 figure) → 2.0 × 10³',
  },
  sf_lost_placeholders: {
    id: 'sf_lost_placeholders',
    title: 'Rounding never changes the size',
    lesson: 'After rounding a big number, fill the dropped places with placeholder zeros so it stays the same size.',
    example: '12345 to 2 figures → 12 ✗ → 12000',
  },
  sf_exact_limited: {
    id: 'sf_exact_limited',
    title: 'Exact numbers never limit',
    lesson: 'Counted things and defined conversions are exact: unlimited significant figures. Only measurements limit the answer.',
    example: '3 beakers × 2.45 g → 7 g ✗ → 7.35 g (the 3 is counted)',
  },
  sf_rounded_early: {
    id: 'sf_rounded_early',
    title: 'Round once, at the end',
    lesson: 'Carry every digit through the middle steps, note how precise each one is, and round only the final answer. Early rounding piles up error.',
    example: '(11.07 + 1.1) × 2.115: 12.2 × 2.115 → 25.8 ✗; 12.17 × 2.115 → 25.7',
  },
  sf_sci_changed_figures: {
    id: 'sf_sci_changed_figures',
    title: 'Converting keeps every figure',
    lesson: 'Changing notation moves the decimal point and nothing else. The number of significant figures stays exactly the same.',
    example: '0.00450 → 4.5 × 10⁻³ ✗ → 4.50 × 10⁻³',
  },
  sf_sci_exponent: {
    id: 'sf_sci_exponent',
    title: 'Count the jumps of the decimal point',
    lesson: 'The power of ten is how many places the point moved: positive for big numbers, negative for small ones.',
    example: '0.00450 → 4.50 × 10³ ✗ → 4.50 × 10⁻³',
  },
  sf_sci_form: {
    id: 'sf_sci_form',
    title: 'One nonzero digit in front',
    lesson: 'Scientific notation has exactly one nonzero digit before the decimal point, so the coefficient is at least 1 and less than 10.',
    example: '45.0 × 10⁻⁴ ✗ → 4.50 × 10⁻³',
  },
  // --- atomic structure (engine/atoms; chemistry) ---
  at_neutrons_as_mass_number: {
    id: 'at_neutrons_as_mass_number',
    title: 'Neutrons = mass number − atomic number',
    lesson: 'The mass number counts protons AND neutrons together. Take the protons away and what is left is the neutrons.',
    example: '³⁷₁₇Cl: 37 neutrons ✗ → 37 − 17 = 20 neutrons',
  },
  at_swapped_a_z: {
    id: 'at_swapped_a_z',
    title: 'Mass number on top, atomic number below',
    lesson: 'In a nuclear symbol the mass number sits on top and the atomic number underneath. The atomic number is the proton count; the mass number adds the neutrons, so it is the bigger one.',
    example: '³⁷₁₇Cl: 37 protons ✗ → 17 protons',
  },
  at_electrons_ignored_charge: {
    id: 'at_electrons_ignored_charge',
    title: 'An ion’s charge changes the electrons',
    lesson: 'A neutral atom has as many electrons as protons, but an ion has gained or lost some. Electrons = protons − charge.',
    example: 'Cl⁻: 17 electrons ✗ → 17 − (−1) = 18 electrons',
  },
  at_charge_sign_flipped: {
    id: 'at_charge_sign_flipped',
    title: 'Extra electrons make it negative',
    lesson: 'Electrons carry the negative charge: gaining them makes an ion negative, losing them makes it positive. Charge = protons − electrons.',
    example: 'Na⁺: 12 electrons ✗ → 11 − 1 = 10 electrons',
  },
  at_protons_changed_for_ion: {
    id: 'at_protons_changed_for_ion',
    title: 'Only the electrons change in an ion',
    lesson: 'An atom becomes an ion by gaining or losing electrons; the nucleus is not touched. The protons stay at the atomic number whatever the charge.',
    example: 'Na⁺: 10 protons ✗ → 11 protons (and 10 electrons)',
  },
  at_element_from_electrons: {
    id: 'at_element_from_electrons',
    title: 'The protons pick the element',
    lesson: 'The atomic number is the number of protons, and it alone decides which element you have. The electrons only decide the charge.',
    example: '11 p, 10 e: Ne ✗ → Na⁺ (11 protons is sodium)',
  },
  at_mass_protons_electrons: {
    id: 'at_mass_protons_electrons',
    title: 'Electrons are left out of the mass number',
    lesson: 'The mass number counts the particles in the nucleus: protons plus neutrons. Electrons are almost weightless and are never counted in it.',
    example: '11 p, 12 n, 10 e: A = 21 ✗ → A = 11 + 12 = 23',
  },
  at_mass_neutrons_only: {
    id: 'at_mass_neutrons_only',
    title: 'The mass number counts the protons too',
    lesson: 'Mass number = protons + neutrons: both kinds of particle in the nucleus. The neutrons alone are only part of it.',
    example: '11 p, 12 n: A = 12 ✗ → A = 11 + 12 = 23',
  },
  at_symbol_case: {
    id: 'at_symbol_case',
    title: 'Capital letter first, lowercase second',
    lesson: 'An element symbol starts with a capital letter, and a second letter is always lowercase. The case carries meaning: Co is cobalt, but CO is carbon and oxygen together.',
    example: 'CL ✗ → Cl     cl ✗ → Cl',
  },
  at_unweighted_average: {
    id: 'at_unweighted_average',
    title: 'Weigh each isotope by how common it is',
    lesson: 'Average atomic mass is a weighted average: a common isotope pulls the average toward its own mass. Adding the masses and dividing by how many there are treats a rare isotope like a common one.',
    example: 'Cl: (34.969 + 36.966) ÷ 2 = 35.97 ✗ → 35.45 u',
  },
  at_percent_not_decimal: {
    id: 'at_percent_not_decimal',
    title: 'Turn the percent into a decimal first',
    lesson: 'A percent means "out of 100", so divide by 100 before multiplying: 75.76% becomes 0.7576. Skipping that makes the answer 100 times too big.',
    example: 'Cl: 34.969 × 75.76 + 36.966 × 24.24 = 3545 ✗ → 35.45 u',
  },
  at_mass_numbers_used: {
    id: 'at_mass_numbers_used',
    title: 'Use the isotopic masses, not the mass numbers',
    lesson: 'A mass number is a count of protons and neutrons, always a whole number. The average needs each isotope’s actual mass in u, from the table.',
    example: 'Cl: 35 × 0.7576 + 37 × 0.2424 = 35.48 ✗ → 35.45 u',
  },
  at_isotope_left_out: {
    id: 'at_isotope_left_out',
    title: 'Every isotope counts',
    lesson: 'The weighted average needs one term for every isotope in the table, even a rare one. Leaving one out makes the answer too small.',
    example: 'Mg: leaving out Mg-25 gives 21.81 ✗ → 24.31 u',
  },
  at_assumed_even_split: {
    id: 'at_assumed_even_split',
    title: 'The average tells you it is not 50/50',
    lesson: 'Two isotopes are half and half only when the average sits exactly halfway between their masses. The closer the average is to one isotope, the more of that isotope there is.',
    example: 'Cu, average 63.546 u: 50% and 50% ✗ → 69.15% Cu-63, 30.85% Cu-65',
  },
  at_abundance_swapped: {
    id: 'at_abundance_swapped',
    title: 'Match each percent to its isotope',
    lesson: 'The average sits closer to the more abundant isotope, so the isotope nearer the average gets the bigger percent.',
    example: 'Cl-35 24.24%, Cl-37 75.76% ✗ → Cl-35 75.76%, Cl-37 24.24%',
  },
  at_abundance_sum: {
    id: 'at_abundance_sum',
    title: 'The abundances add up to 100%',
    lesson: 'Every atom of the element is one isotope or the other, so the percents must total exactly 100%. Once you have one, the other is 100% minus it.',
    example: '69.15% and 31.85% ✗ (101%) → 69.15% and 30.85%',
  },
  // --- reading a graph (content/modules/graphFeatures; precalculus) ---
  gf_union_between_points: {
    id: 'gf_union_between_points',
    title: 'U joins intervals, not points',
    lesson:
      'U joins intervals — sets of numbers. Between points that line reads as two intervals, and a point written that way can run backwards. A list of points uses "and" or a comma.',
    example: '(-2.5, -5.5) U (7.25, -9.25) ✗ → (-2.5, -5.5) and (7.25, -9.25)',
  },
  gf_y_for_intervals: {
    id: 'gf_y_for_intervals',
    title: 'Increasing uses x-values',
    lesson:
      'Increasing and decreasing are about the x-axis: the inputs where the graph climbs or falls. The heights (y-values) name the points, not the intervals.',
    example: '(-5.5, 3.25) U (-9.25, inf) ✗ → (-2.5, 2) U (7.25, inf)',
  },
  gf_brackets_at_turns: {
    id: 'gf_brackets_at_turns',
    title: 'Parentheses at a turning point',
    lesson:
      'At a turning point the graph is flat for an instant, so it is not strictly increasing or decreasing there. Those x-values get parentheses, not brackets.',
    example: '[-2.5, 2] U [7.25, inf) ✗ → (-2.5, 2) U (7.25, inf)',
  },
  gf_swapped_inc_dec: {
    id: 'gf_swapped_inc_dec',
    title: 'Increasing and decreasing are swapped',
    lesson:
      'Increasing is where the graph climbs as you read left to right. Decreasing is where it falls. The two intervals trade places if those words are swapped.',
    example: 'increasing (-inf, -2.5) U (2, 7.25) ✗ → (-2.5, 2) U (7.25, inf)',
  },
  gf_global_on_ray: {
    id: 'gf_global_on_ray',
    title: 'No highest point if it keeps rising',
    lesson:
      'A global max is the highest point the graph ever reaches. If an end climbs forever toward +∞, there is no highest point — write none. If an end falls forever toward −∞, there is no global min.',
    example: 'global max (2, 3.25) ✗ → none',
  },
  gf_global_not_local: {
    id: 'gf_global_not_local',
    title: 'A global max or min is also local',
    lesson:
      'A turning point that is the global min is still a local min, and the same for a max. It belongs in the local list too.',
    example: 'local min only (-2.5, -5.5) ✗ → (-2.5, -5.5) and (7.25, -9.25)',
  },
  gf_not_turning_point: {
    id: 'gf_not_turning_point',
    title: 'Only the turning points',
    lesson:
      'A local max or min is a labelled turning point, where the graph changes from climbing to falling or back. A point that is not a turn does not count.',
    example: 'local max (0, 0) ✗ → (2, 3.25)',
  },
  gf_swapped_coordinates: {
    id: 'gf_swapped_coordinates',
    title: 'x first, then y',
    lesson: 'A point is (x, y): how far across, then how high. Reading the label backwards swaps the coordinates.',
    example: '(-5.5, -2.5) ✗ → (-2.5, -5.5)',
  },
  // --- domain, range, composition (content maps FunctionMistakeKind → fn_*; engine writes the witness) ---
  fn_domain_forgot_denominator: {
    id: 'fn_domain_forgot_denominator',
    title: 'A denominator can never be 0',
    lesson: 'If a formula divides, the bottom is not allowed to be 0, even when everything else looks fine. Solve bottom ≠ 0 and leave those x-values out.',
    example: 'sqrt(x + 2)/(x − 3) → [−2, ∞) ✗ → [−2, 3) ∪ (3, ∞)',
  },
  fn_domain_root_strict: {
    id: 'fn_domain_root_strict',
    title: 'The square root of 0 is 0',
    lesson: 'An even root needs its inside to be at least 0, and 0 itself is allowed. A parenthesis where a bracket belongs drops a point where f is 0, which is defined.',
    example: 'sqrt(x + 2) → (−2, ∞) ✗ → [−2, ∞)',
  },
  fn_domain_root_denominator_zero: {
    id: 'fn_domain_root_denominator_zero',
    title: 'A root in a denominator must be positive',
    lesson: 'An even root in a denominator cannot be 0, because that is dividing by 0. The inside has to be strictly greater than 0, not greater than or equal.',
    example: '1/sqrt(x − 1) → [1, ∞) ✗ → (1, ∞)',
  },
  fn_domain_odd_root_restricted: {
    id: 'fn_domain_odd_root_restricted',
    title: 'Cube roots take negative numbers',
    lesson: 'The cube root of a negative number is a real number (cbrt(−8) = −2). Only even roots, like square roots, need the inside to be at least 0.',
    example: 'cbrt(x − 2) → [2, ∞) ✗ → (−∞, ∞)',
  },
  fn_domain_no_flip: {
    id: 'fn_domain_no_flip',
    title: 'Dividing by a negative flips the inequality',
    lesson: 'When you divide both sides by a negative number, the inequality sign flips. A negative in front of x inside a root is exactly that step.',
    example: 'sqrt(−2x + 6) → [3, ∞) ✗ → (−∞, 3]',
  },
  fn_domain_gave_range: {
    id: 'fn_domain_gave_range',
    title: 'That is the range, not the domain',
    lesson: 'The domain is the set of inputs x that f accepts. The range is the set of outputs. They answer different questions.',
    example: 'sqrt(−2x + 6) → [0, ∞) ✗ → (−∞, 3]',
  },
  fn_domain_denominator_nonneg: {
    id: 'fn_domain_denominator_nonneg',
    title: 'A denominator only has to be nonzero',
    lesson: 'The bottom of a fraction can be negative. It just cannot be 0. Writing bottom ≥ 0 (or > 0) throws away half the inputs.',
    example: '1/(x − 3) → [3, ∞) ✗ → (−∞, 3) ∪ (3, ∞)',
  },
  fn_range_gave_domain: {
    id: 'fn_range_gave_domain',
    title: 'That is the domain, not the range',
    lesson: 'The range is the set of outputs y = f(x). The domain is the inputs. A set of x-values is not the range.',
    example: '−2sqrt(x + 1) + 5 → [−1, ∞) ✗ → (−∞, 5]',
  },
  fn_range_reflection_ignored: {
    id: 'fn_range_reflection_ignored',
    title: 'A negative in front flips the outputs',
    lesson: 'Multiplying by a negative turns the graph upside down. A downward parabola, or a negative in front of a square root or absolute value, sends the outputs the other way.',
    example: '−2sqrt(x + 1) + 5 → [5, ∞) ✗ → (−∞, 5]',
  },
  fn_range_included_asymptote: {
    id: 'fn_range_included_asymptote',
    title: 'The asymptote value is not an output',
    lesson: 'A horizontal asymptote is a height the graph gets close to and never reaches. That y-value is left out of the range.',
    example: '3/(x − 2) + 1 → (−∞, ∞) ✗ → (−∞, 1) ∪ (1, ∞)',
  },
  fn_compose_no_parens: {
    id: 'fn_compose_no_parens',
    title: 'Put the inside function in parentheses',
    lesson: 'When you substitute, the whole of g(x) goes where x was, in parentheses. Without them, an exponent or a coefficient only reaches part of g.',
    example: 'x − 3^2 + 1 ✗ → (x − 3)^2 + 1',
  },
  fn_compose_partial_sub: {
    id: 'fn_compose_partial_sub',
    title: 'Every x in f becomes g(x)',
    lesson: 'Substitution replaces every x in f, not just the first one. If any x is left as itself, that term never saw g.',
    example: '(x + 1)^2 + 2x ✗ → (x + 1)^2 + 2(x + 1)',
  },
  fn_compose_product: {
    id: 'fn_compose_product',
    title: 'Composition is not multiplication',
    lesson: 'f(g(x)) puts g inside f. It is not f(x) times g(x).',
    example: '(x^2 + 1)(x − 3) ✗ → (x − 3)^2 + 1',
  },
  fn_compose_reversed: {
    id: 'fn_compose_reversed',
    title: 'f ∘ g means f on the outside',
    lesson: '(f ∘ g)(x) is f(g(x)): g goes first, then f. g(f(x)) is the other order.',
    example: '(x^2 + 1) − 3 ✗ → (x − 3)^2 + 1',
  },
  fn_compose_sum: {
    id: 'fn_compose_sum',
    title: 'Composition is not addition',
    lesson: 'f(g(x)) puts g inside f. Adding the two formulas is f(x) + g(x), a different function.',
    example: 'x^2 + 1 + (x − 3) ✗ → (x − 3)^2 + 1',
  },
  fn_value_product: {
    id: 'fn_value_product',
    title: '(f ∘ g)(a) is not f(a) times g(a)',
    lesson: 'A number in parentheses means plug it in, from the inside out: g(a) first, then f of that result. Multiplying f(a) by g(a) is a different calculation.',
    example: 'f(2) · g(2) = 27 ✗ → f(g(2)) = 11',
  },
  fn_value_reversed: {
    id: 'fn_value_reversed',
    title: 'Inside first: g(a), then f',
    lesson: '(f ∘ g)(a) works from the inside out. g(f(a)) is the other order, (g ∘ f)(a).',
    example: 'g(f(2)) = 80 ✗ → f(g(2)) = 11',
  },
  fn_composite_domain_simplified: {
    id: 'fn_composite_domain_simplified',
    title: 'Simplifying can hide a restriction',
    lesson: 'The domain of f ∘ g is not whatever the simplified formula allows. x has to be in the domain of g first, and then g(x) has to be in the domain of f.',
    example: 'f(x) = x^2, g(x) = sqrt(x) → (−∞, ∞) ✗ → [0, ∞)',
  },
  fn_composite_domain_inner_only: {
    id: 'fn_composite_domain_inner_only',
    title: 'g(x) still has to be allowed into f',
    lesson: 'Being in the domain of g is only half of it. The output g(x) also has to be an allowed input for f.',
    example: 'f(x) = 1/(x − 2), g(x) = sqrt(x) → [0, ∞) ✗ → [0, 4) ∪ (4, ∞)',
  },
  // --- transformations, piecewise, average rate (content maps TransformMistakeKind; engine writes the witness) ---
  tr_h_shift_reversed: {
    id: 'tr_h_shift_reversed',
    title: 'x − h moves right, not left',
    lesson: 'The number inside f does the opposite of what the sign looks like. f(x − 3) moves the graph right 3, because x has to be 3 bigger before the inside is 0.',
    example: 'shift left 3 ✗ → shift right 3',
  },
  tr_v_shift_reversed: {
    id: 'tr_v_shift_reversed',
    title: 'Added after f moves up',
    lesson: 'A number added after f moves the graph up by that number. f(x) + 1 is up 1, not down 1. A minus after f is what moves it down.',
    example: 'shift down 1 ✗ → shift up 1',
  },
  tr_h_factor_inverted: {
    id: 'tr_h_factor_inverted',
    title: 'f(2x) squeezes toward the y-axis',
    lesson: 'A number multiplying x inside f divides the x-values. f(2x) is a horizontal compression by 1/2, not a stretch by 2. A stretch would be f(x/2).',
    example: 'stretch horizontally by 2 ✗ → compress horizontally by 1/2',
  },
  tr_v_factor_inverted: {
    id: 'tr_v_factor_inverted',
    title: 'The number in front multiplies the heights',
    lesson: 'The number in front of f multiplies every y-value. (1/2)f(x) is a vertical compression by 1/2. Reading 1/2 as a stretch by 2 turns the factor upside down.',
    example: 'stretch vertically by 2 ✗ → compress vertically by 1/2',
  },
  tr_reflection_wrong_axis: {
    id: 'tr_reflection_wrong_axis',
    title: 'The minus sign has a side',
    lesson: '−f(x) reflects over the x-axis: the minus is in front, so it changes y. f(−x) reflects over the y-axis: the minus is on x. They are not the same move.',
    example: 'reflect over the y-axis ✗ → reflect over the x-axis',
  },
  tr_unfactored_shift: {
    id: 'tr_unfactored_shift',
    title: 'Factor the inside before you read the shift',
    lesson: 'f(2x − 6) is not a shift of 6. Factor first: 2x − 6 = 2(x − 3), so the shift is right 3. The number you see before factoring is the shift times the factor.',
    example: 'shift right 6 ✗ → shift right 3',
  },
  tr_missing_reflection: {
    id: 'tr_missing_reflection',
    title: 'A minus sign is a reflection',
    lesson: 'A minus in front of f, or on x inside f, flips the graph. Leaving that reflection out keeps the graph the original way up, or on the original side of the y-axis.',
    example: '2(x − 3)^2 + 1 ✗ → −2(x − 3)^2 + 1',
  },
  tr_missing_step: {
    id: 'tr_missing_step',
    title: 'Every piece of the formula is a step',
    lesson: 'A shift, a stretch, and a reflection each come from their own part of the formula. If the formula has it, the list needs it.',
    example: 'shift right 3 only ✗ → shift right 3 and shift up 1',
  },
  tr_extra_step: {
    id: 'tr_extra_step',
    title: 'Only the steps the formula actually has',
    lesson: 'A transformation that is not in the formula does not happen. If nothing is added after f, there is no vertical shift.',
    example: 'shift right 3 and shift up 2 ✗ → shift right 3',
  },
  tr_h_order: {
    id: 'tr_h_order',
    title: 'Divide x first, then shift',
    lesson: 'The number inside f is already multiplied, so undo it first: divide the x-coordinate by b, then add h. Shifting before you divide does (p + h)/b, which is a different point.',
    example: '(7/2, −31) ✗ → (5, −31)',
  },
  tr_v_order: {
    id: 'tr_v_order',
    title: 'Multiply y first, then shift',
    lesson: 'The number in front of f acts before the number added after it. Multiply the y-coordinate by a, then add k. Doing the shift first, a·(q + k), uses the shift on the wrong number.',
    example: '(5, −34) ✗ → (5, −31)',
  },
  tr_factors_swapped: {
    id: 'tr_factors_swapped',
    title: 'a acts on y, b acts on x',
    lesson: 'The number in front of f multiplies heights. The number inside with x changes the inputs. Swapping them puts the vertical factor on x and the horizontal factor on y.',
    example: '(−5, 9) ✗ → (5, −31)',
  },
  tr_v_factor_inside: {
    id: 'tr_v_factor_inside',
    title: 'The number in front stays in front',
    lesson: 'a multiplies the output of f, so it goes in front of the parentheses. Inside the parentheses it multiplies x instead, which is a horizontal change.',
    example: '(−2(x − 3))^2 + 1 ✗ → −2(x − 3)^2 + 1',
  },
  tr_v_shift_inside: {
    id: 'tr_v_shift_inside',
    title: 'The vertical shift stays outside',
    lesson: 'k is added after f, so it sits outside the parentheses. Putting it inside changes x, not the height.',
    example: '−2(x − 2)^2 ✗ → −2(x − 3)^2 + 1',
  },
  pw_piecewise_boundary: {
    id: 'pw_piecewise_boundary',
    title: 'A boundary belongs to the piece that includes it',
    lesson: 'At a point where two pieces meet, < leaves the endpoint out and ≤ keeps it. Use the piece whose inequality actually includes the number.',
    example: 'f(2) = 4 ✗ → f(2) = 5',
  },
  pw_piecewise_wrong_piece: {
    id: 'pw_piecewise_wrong_piece',
    title: 'Use the piece whose interval contains x',
    lesson: 'Each formula only applies on its own interval. If x is not in that piece, that formula is the wrong one, even when it is easy to compute.',
    example: 'f(3) = 9 ✗ → f(3) = 7',
  },
  pw_piecewise_value_where_undefined: {
    id: 'pw_piecewise_value_where_undefined',
    title: 'No piece means undefined',
    lesson: 'If x is left out of every piece, f(x) is undefined. A formula from a neighboring piece does not fill the gap.',
    example: 'f(5) = 11 ✗ → undefined',
  },
  pw_piecewise_undefined_where_defined: {
    id: 'pw_piecewise_undefined_where_defined',
    title: 'A piece includes this x',
    lesson: 'If x satisfies one piece’s inequality, f(x) is that formula’s value. “Undefined” is only for an x that every piece leaves out.',
    example: 'f(1) = undefined ✗ → f(1) = 1',
  },
  rate_sign_flipped: {
    id: 'rate_sign_flipped',
    title: 'Subtract the same way on the top and the bottom',
    lesson: 'Average rate of change is (f(b) − f(a)) / (b − a). Flipping one subtraction and not the other flips the sign of the slope.',
    example: '−5 ✗ → 5',
  },
  rate_no_division: {
    id: 'rate_no_division',
    title: 'Divide by the change in x',
    lesson: 'f(b) − f(a) is only how much the height changed. The rate is that change divided by how far x moved, b − a.',
    example: '15 ✗ → 5',
  },
  rate_inverted: {
    id: 'rate_inverted',
    title: 'Rise over run, not run over rise',
    lesson: 'The average rate of change is the change in y over the change in x. Putting b − a on top gives the reciprocal of the slope.',
    example: '1/5 ✗ → 5',
  },
  rate_divided_by_b: {
    id: 'rate_divided_by_b',
    title: 'Divide by b − a, not by b',
    lesson: 'The run is how far apart the two x-values are, b − a. Dividing by b alone forgets to subtract a.',
    example: '15/4 ✗ → 5',
  },
  // --- electrons and light (content/modules/electrons; chemistry ch. 5) ---
  lt_no_conversion: {
    id: 'lt_no_conversion',
    title: 'Convert nanometers to meters first',
    lesson: 'The speed of light is in meters per second, so a wavelength in nanometers has to become meters before you divide. Multiply by 10⁻⁹: the decimal point jumps nine places left.',
    example: '620 nm → 620 m ✗ → 6.20 × 10⁻⁷ m',
  },
  lt_conversion_backwards: {
    id: 'lt_conversion_backwards',
    title: '10⁻⁹ goes with nanometers, not 10⁹',
    lesson: 'A nanometer is a billionth of a meter, so nm becomes m by multiplying by 10⁻⁹. Multiplying by 10⁹, or dividing by 10⁻⁹ when you meant the other way, sends the decimal point the wrong direction.',
    example: '620 nm → 6.20 × 10¹¹ m ✗ → 6.20 × 10⁻⁷ m',
  },
  lt_multiplied: {
    id: 'lt_multiplied',
    title: 'c and λ are divided, not multiplied',
    lesson: 'The wave equation is c = λν, so frequency is c ÷ λ and wavelength is c ÷ ν. Multiplying those two makes a huge number with the wrong units.',
    example: 'ν = c × λ ✗ → ν = c ÷ λ',
  },
  lt_inverted: {
    id: 'lt_inverted',
    title: 'The speed of light goes on top',
    lesson: 'c is the big number, so it is the numerator: ν = c ÷ λ and λ = c ÷ ν. Putting c on the bottom flips the answer into a tiny fraction.',
    example: 'ν = λ ÷ c ✗ → ν = c ÷ λ',
  },
  lt_energy_divided: {
    id: 'lt_energy_divided',
    title: 'A photon’s energy is h times ν',
    lesson: 'E = hν is a product. Dividing h by the frequency, or the frequency by h, does not give the energy of one photon.',
    example: 'E = h ÷ ν ✗ → E = h × ν',
  },
  lt_energy_no_c: {
    id: 'lt_energy_no_c',
    title: 'From a wavelength, multiply by c too',
    lesson: 'E = hν and ν = c ÷ λ, so together E = hc ÷ λ. Using E = h ÷ λ leaves out the speed of light.',
    example: 'E = h ÷ λ ✗ → E = hc ÷ λ',
  },
  lt_wrong_unit: {
    id: 'lt_wrong_unit',
    title: 'That number is in the other unit',
    lesson: 'Meters and nanometers name the same length at different sizes. A result in m is a billion times smaller than the same length in nm, so the unit the question asked for is part of the answer.',
    example: '6.67 × 10⁻⁷ nm ✗ → 667 nm',
  },
  lt_order_reversed: {
    id: 'lt_order_reversed',
    title: 'That ranking runs the other way',
    lesson: 'Frequency and energy rise as wavelength falls. The longest wavelength (radio, or red) is the lowest frequency and energy; the shortest (gamma, or violet) is the highest. Reversing the list, or ranking by wavelength when frequency or energy was asked, gives the opposite order.',
    example: 'increasing frequency: radio → gamma ✗ → gamma → radio',
  },
  // --- electron configurations (engine/econfig; content/modules/electrons) ---
  ec_electron_count: {
    id: 'ec_electron_count',
    title: 'Count the electrons up to the atomic number',
    lesson: 'A neutral atom has as many electrons as its atomic number. Add the superscripts: the total has to match. One too many or one too few means a subshell was left short or overfilled.',
    example: 'Fe (26 electrons): 4s² 3d⁵ ✗ → 4s² 3d⁶',
  },
  ec_subshell_overfilled: {
    id: 'ec_subshell_overfilled',
    title: 'A subshell only holds so many',
    lesson: 'An s subshell holds 2 electrons, a p subshell holds 6, and a d subshell holds 10. A higher count does not fit, however many electrons are still left to place.',
    example: '2p⁷ ✗ → 2p⁶',
  },
  ec_subshell_nonexistent: {
    id: 'ec_subshell_nonexistent',
    title: 'That subshell does not exist',
    lesson: 'There is no 1p, 2d or 3f subshell. The letter cannot be as high as the shell number: shell 1 has only s, shell 2 has s and p, shell 3 has s, p and d.',
    example: '2d¹ ✗ → 3s¹',
  },
  ec_filling_order: {
    id: 'ec_filling_order',
    title: 'Subshells fill in a fixed order',
    lesson: 'Electrons fill the lowest energy subshell that still has room: 1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p. 4s fills before 3d, and 3d fills before 4p. Do not skip ahead, and do not put electrons in 3d while 4s is still empty.',
    example: 'K: [Ar] 3d¹ ✗ → [Ar] 4s¹',
  },
  ec_exception_missed: {
    id: 'ec_exception_missed',
    title: 'Chromium and copper are exceptions',
    lesson: 'Chromium and copper do not follow the plain filling order. A half-filled 3d⁵ or a full 3d¹⁰ is extra stable, so one electron moves from 4s to 3d.',
    example: 'Cr: [Ar] 4s² 3d⁴ ✗ → [Ar] 4s¹ 3d⁵',
  },
  ec_exception_misapplied: {
    id: 'ec_exception_misapplied',
    title: 'Only chromium and copper move an electron',
    lesson: 'The move from 4s to 3d is only for chromium and copper among the first 36 elements. The other elements from scandium to zinc keep 4s² and put the rest in 3d.',
    example: 'Fe: [Ar] 4s¹ 3d⁷ ✗ → [Ar] 4s² 3d⁶',
  },
  ec_ion_charge_ignored: {
    id: 'ec_ion_charge_ignored',
    title: 'The charge changes the electron count',
    lesson: 'An ion is not the neutral atom. A positive charge means electrons were lost, and a negative charge means electrons were gained, so both the configuration and which element it is shift by that charge.',
    example: 'Fe²⁺ written as neutral iron ✗ → Fe²⁺ is [Ar] 3d⁶',
  },
  ec_ion_wrong_direction: {
    id: 'ec_ion_wrong_direction',
    title: 'Positive ions lose electrons',
    lesson: 'A positive ion has lost electrons, so it has fewer than the neutral atom. A negative ion has gained them. Adding electrons for a cation, or removing them for an anion, runs the charge backwards.',
    example: 'Na⁺: [Ne] 3s² ✗ → [Ne]',
  },
  ec_ion_removed_from_3d: {
    id: 'ec_ion_removed_from_3d',
    title: '4s electrons leave before 3d',
    lesson: 'When a transition metal becomes a positive ion, electrons leave the highest shell number first. 4s is the outermost shell, so the 4s electrons leave before any 3d electron, even though 4s filled first.',
    example: 'Fe²⁺: [Ar] 4s² 3d⁴ ✗ → [Ar] 3d⁶',
  },
  ec_ion_wrong_number: {
    id: 'ec_ion_wrong_number',
    title: 'The charge says how many electrons moved',
    lesson: 'The size of the charge is the number of electrons gained or lost. A 3+ ion has lost three, not one or two, and a 2− ion has gained two.',
    example: 'Fe³⁺: [Ar] 3d⁶ ✗ → [Ar] 3d⁵',
  },
  ec_core_wrong: {
    id: 'ec_core_wrong',
    title: 'The brackets hold the noble gas before it',
    lesson: 'Noble-gas shorthand starts from the noble gas just before the element, the one whose electrons are all inside. An earlier noble gas, or an element that is not a noble gas, is the wrong core.',
    example: 'Ca: [Ne] 4s² ✗ → [Ar] 4s²',
  },
  ec_core_not_earlier: {
    id: 'ec_core_not_earlier',
    title: 'The core is an earlier noble gas',
    lesson: 'The symbol in brackets has to be a noble gas that comes before this species, with no more electrons than it has. The element itself, or a noble gas after it, cannot be the core.',
    example: 'Ar: [Ar] ✗ → [Ne] 3s² 3p⁶',
  },
  ec_valence_total_electrons: {
    id: 'ec_valence_total_electrons',
    title: 'Valence electrons are only the outer shell',
    lesson: 'The atomic number counts every electron in the atom. Valence electrons are only the ones in the outermost shell, the highest shell number. Inner shells do not count.',
    example: 'Cl: 17 ✗ → 7',
  },
  ec_valence_last_subshell: {
    id: 'ec_valence_last_subshell',
    title: 'Count the whole outer shell',
    lesson: 'The outermost shell can hold more than one subshell. Valence electrons are every electron in that shell, so the s electrons count together with the p electrons. The last subshell alone is not the whole shell.',
    example: 'Cl: 5 (3p only) ✗ → 7',
  },
  ec_hund_broken: {
    id: 'ec_hund_broken',
    title: 'One electron per box before any pair',
    lesson: "Hund's rule: the orbitals of a subshell have the same energy, so each box gets one electron, all with the same spin, before any box gets a second. Pairing early, or pointing the single arrows different ways, leaves the wrong electrons unpaired.",
    example: '2p⁴: [↑↓] [↑↓] [ ] ✗ → [↑↓] [↑] [↑]',
  },
  ec_pauli_broken: {
    id: 'ec_pauli_broken',
    title: 'Two arrows in one box point the same way',
    lesson: 'The Pauli exclusion principle: an orbital holds at most two electrons, and those two must have opposite spins. Two arrows the same way, or more than two arrows in one box, cannot be right.',
    example: '[↑↑] ✗ → [↑↓]',
  },
  ec_unpaired_from_wrong_diagram: {
    id: 'ec_unpaired_from_wrong_diagram',
    title: "Unpaired electrons follow Hund's rule",
    lesson: 'An unpaired electron sits alone in a box. Pairing electrons up first makes too many pairs and too few unpaired electrons. Fix the diagram, and the count follows.',
    example: 'N: 1 unpaired ✗ → 3 unpaired',
  },
  // --- polynomials (engine/polynomials; precalculus Unit 2). One entry per PolyMistakeKind. ---
  poly_cs_no_factor_a: {
    id: 'poly_cs_no_factor_a',
    title: 'Factor a out before you halve',
    lesson: 'When the number in front of x^2 is not 1, factor it out of both x-terms before you halve: 2x^2 − 12x = 2(x^2 − 6x), and it is the −6 you halve, not the −12. It is the same rule as x = −b/(2a): divide by 2a, not by 2.',
    example: '2(x − 6)^2 − 23 ✗ → 2(x − 3)^2 − 5',
  },
  poly_cs_unbalanced: {
    id: 'poly_cs_unbalanced',
    title: 'What you add, you also take away',
    lesson: 'Adding a number to make a perfect square changes the value of the expression, so subtract the same amount straight away. Inside a( ) the number you added is worth a times as much.',
    example: '2(x − 3)^2 + 13 ✗ → 2(x − 3)^2 − 5',
  },
  poly_cs_constant_not_scaled: {
    id: 'poly_cs_constant_not_scaled',
    title: 'A number inside a( ) is worth a times as much',
    lesson: 'A number that sits inside a( ) is multiplied by a when it comes out of the parentheses. In 2(x^2 − 6x + 9 − 9) + 13 the −9 leaves as 2·(−9) = −18, so the constant is 13 − 18, not 13 − 9.',
    example: '2(x − 3)^2 + 4 ✗ → 2(x − 3)^2 − 5',
  },
  poly_cs_half_or_square: {
    id: 'poly_cs_half_or_square',
    title: 'Half of b, then square it',
    lesson: 'The number that completes the square is (b/2)^2: halve the x-coefficient first, then square the half. The half goes inside the square, and its square is what you add and subtract. For x^2 − 6x that is −3 inside and 9 added, not 18 or 36.',
    example: '2(x − 3)^2 − 23 ✗ → 2(x − 3)^2 − 5',
  },
  poly_cs_h_sign: {
    id: 'poly_cs_h_sign',
    title: 'The sign inside the square is opposite to h',
    lesson: 'Vertex form is a(x − h)^2 + k, with the minus built in. (x − 3)^2 is zero at x = 3, so h = 3; (x + 3)^2 would mean h = −3. The number inside the square is half of the x-coefficient with its own sign: half of −6 is −3.',
    example: '(−3, −5) ✗ → (3, −5)',
  },
  poly_cs_vertex_swapped: {
    id: 'poly_cs_vertex_swapped',
    title: 'The vertex is (h, k): x first',
    lesson: 'h comes from the square and says where the parabola turns. k is the number added after the square and says how high the turn is. Write the point as (h, k), x-coordinate first.',
    example: '(−5, 3) ✗ → (3, −5)',
  },
  poly_sd_wrong_sign_c: {
    id: 'poly_sd_wrong_sign_c',
    title: 'The box holds the zero of the divisor',
    lesson: 'Dividing by x − c puts c in the box: the number that makes the divisor zero. For x − 2 that is 2, and for x + 2 it is −2. The same number goes into f for the remainder theorem and the factor theorem.',
    example: 'x − 2: −2 in the box ✗ → 2 in the box',
  },
  poly_sd_missing_placeholder: {
    id: 'poly_sd_missing_placeholder',
    title: 'A missing power still needs a 0',
    lesson: 'Every power of x gets a place in the top row, from the highest down to the constant. When a term is missing, write 0 for it, or every later number lines up with the wrong power.',
    example: '2x^3 − 3x^2 − 5: 2, −3, −5 ✗ → 2, −3, 0, −5',
  },
  poly_sd_subtracted: {
    id: 'poly_sd_subtracted',
    title: 'Synthetic division adds',
    lesson: 'In each column you multiply, write the product under the next coefficient, and add. The sign change is already built into the number in the box, so subtracting undoes it.',
    example: 'product 2 under 0: 0 − 2 = −2 ✗ → 0 + 2 = 2',
  },
  poly_sd_first_coefficient: {
    id: 'poly_sd_first_coefficient',
    title: 'Bring the first coefficient straight down',
    lesson: 'Nothing goes under the first coefficient, so it drops to the bottom row unchanged. The multiplying starts with that number, for the second column.',
    example: '4, 5, 10, 15 ✗ → 2, 1, 2, −1',
  },
  poly_sd_quotient_degree: {
    id: 'poly_sd_quotient_degree',
    title: 'The quotient is one degree lower',
    lesson: 'Dividing by x − c takes one power of x away. A cubic leaves a quadratic, so the bottom-row numbers before the remainder are the coefficients starting at x^2, not at x^3.',
    example: '2x^3 + x^2 + 2x ✗ → 2x^2 + x + 2',
  },
  poly_sd_remainder_last_quotient: {
    id: 'poly_sd_remainder_last_quotient',
    title: 'The remainder is the last number',
    lesson: 'The last number of the bottom row is the remainder. The number just before it is the constant term of the quotient.',
    example: 'bottom row 2, 1, 2, −1: remainder 2 ✗ → remainder −1',
  },
  poly_zero_sign_reversed: {
    id: 'poly_zero_sign_reversed',
    title: 'A zero has the opposite sign to its factor',
    lesson: 'A zero is the x that makes its factor equal 0. (x + 1) is 0 at x = −1, and (x − 3) is 0 at x = 3. Going the other way, a zero at −1 gives the factor (x + 1).',
    example: '(x + 1): zero 1 ✗ → zero −1',
  },
  poly_zero_nonmonic_factor: {
    id: 'poly_zero_nonmonic_factor',
    title: 'Set the whole factor equal to 0',
    lesson: 'When x has a number in front, solve the little equation: 2x − 1 = 0 gives 2x = 1, so x = 1/2. Reading the zero straight off the constant skips the division.',
    example: '(2x − 1): zero 1 ✗ → zero 1/2',
  },
  poly_multiplicity_ignored: {
    id: 'poly_multiplicity_ignored',
    title: 'The exponent is the multiplicity',
    lesson: 'The exponent on a factor says how many times that zero counts. (x + 1)^2 gives x = −1 with multiplicity 2, and a factor with no exponent has multiplicity 1.',
    example: '(x + 1)^2: multiplicity 1 ✗ → multiplicity 2',
  },
  poly_multiplicity_wrong_zero: {
    id: 'poly_multiplicity_wrong_zero',
    title: 'Each exponent belongs to its own factor',
    lesson: 'A multiplicity goes with the zero whose factor carries that exponent. In (x + 1)^2(x − 3) the 2 belongs to x = −1, and x = 3 has multiplicity 1.',
    example: '(x + 1)(x − 3)^2 ✗ → (x + 1)^2(x − 3)',
  },
  poly_cross_touch_swapped: {
    id: 'poly_cross_touch_swapped',
    title: 'Odd crosses, even touches',
    lesson: 'At a zero with odd multiplicity the factor changes sign, so the graph crosses the x-axis. At a zero with even multiplicity the sign stays the same, so the graph touches the axis and turns back.',
    example: '(x + 1)^2: crosses at −1 ✗ → touches at −1',
  },
  poly_end_sign_ignored: {
    id: 'poly_end_sign_ignored',
    title: 'The leading coefficient decides the right end',
    lesson: 'A positive leading coefficient sends the right end up, and a negative one sends it down. The degree only decides whether the left end does the same or the opposite.',
    example: '−2x^6: both ends up ✗ → both ends down',
  },
  poly_end_parity_swapped: {
    id: 'poly_end_parity_swapped',
    title: 'Even degree, same ends. Odd degree, opposite ends',
    lesson: 'An even degree sends both ends the same way, and an odd degree sends them opposite ways. Find the degree by adding the exponents of the factors, not by counting the factors.',
    example: 'degree 6: left up, right down ✗ → both ends down',
  },
  poly_lead_coefficient_omitted: {
    id: 'poly_lead_coefficient_omitted',
    title: 'Keep the number in front',
    lesson: 'The zeros fix the factors, but not how tall the graph is. Put a in front, f(x) = a(x − r1)(x − r2), and use the given point to find it. That number also multiplies the y-intercept.',
    example: '(x + 1)^2(x − 3) ✗ → −2(x + 1)^2(x − 3)',
  },
  poly_rrt_inverted: {
    id: 'poly_rrt_inverted',
    title: 'p over q: the constant goes on top',
    lesson: 'The candidates are p/q, where p is a factor of the constant term and q is a factor of the leading coefficient. Putting the leading coefficient on top turns every fraction upside down.',
    example: '2x^3 − 5x^2 − 4x + 3: ±1/3, ±2/3 ✗ → ±1/2, ±3/2',
  },
  poly_rrt_no_plus_minus: {
    id: 'poly_rrt_no_plus_minus',
    title: 'Every candidate comes with ±',
    lesson: 'A rational zero can be negative as easily as positive, so each fraction p/q is listed with both signs.',
    example: '1, 3, 1/2, 3/2 ✗ → ±1, ±3, ±1/2, ±3/2',
  },
  poly_rrt_integers_only: {
    id: 'poly_rrt_integers_only',
    title: 'Divide by the factors of the leading coefficient',
    lesson: 'When the leading coefficient is not 1, its factors go underneath. Listing only the factors of the constant term leaves out the fractions.',
    example: '±1, ±3 ✗ → ±1, ±3, ±1/2, ±3/2',
  },
  poly_rrt_wrong_coefficients: {
    id: 'poly_rrt_wrong_coefficients',
    title: 'Use the last and the first coefficients',
    lesson: 'p comes from the constant term and q from the leading coefficient. The coefficients in the middle play no part in the list.',
    example: '2x^3 − 5x^2 − 4x + 3: factors of −4 over 2 ✗ → factors of 3 over 2',
  },
  // --- behavioral (ui) ---
  abandoned: {
    id: 'abandoned',
    title: 'Still here?',
    lesson: 'A problem left half-done is a problem half-learned — the hint button is right there.',
    example: '',
  },
}

/** Builds a PatternHit from the catalog, optionally with a concrete witness for this instance. */
export function patternHit(id: ErrorPatternId, witness?: string): PatternHit {
  const info = ERROR_PATTERNS[id]
  return witness ? { ...info, witness } : { ...info }
}
