/**
 * Independent REFERENCE implementation of the significant-figure conventions, used only by
 * `sigfigs-differential.sweep.ts` to cross-check `src/engine/sigfigs`.
 *
 * It shares no code with the engine and works a different way on purpose:
 *   - every value is an exact fraction n/d over BigInt (never a float, never a digit string);
 *   - figures are counted ARITHMETICALLY, from two places (powers of ten):
 *       first significant place = floor(log10 |v|), found by comparing n with d x 10^k;
 *       last significant place  = power - (fraction digits typed)           when a point was typed,
 *                                 power + (10-adic valuation of the integer) when no point was typed;
 *       sigFigs = first - last + 1;
 *   - rounding is one integer division with remainder: tie exactly when 2r = divisor;
 *   - digits for displays are generated by long division.
 *
 * Conventions (the spec): nonzero digits count; captive zeros count; leading zeros never count;
 * trailing zeros count only with a decimal point; in scientific notation the rules apply to the
 * coefficient; exact numbers never limit; multiply/divide keeps the fewest figures; add/subtract
 * keeps the least precise place; mixed work carries every digit and rounds once; half-up on the
 * magnitude, with ties reported.
 */

// ---------------------------------------------------------------------------
// Exact fractions
// ---------------------------------------------------------------------------

export interface Frac {
  /** Numerator, carries the sign. */
  n: bigint
  /** Denominator, always > 0, gcd(n, d) = 1. */
  d: bigint
}

function absBig(a: bigint): bigint {
  return a < 0n ? -a : a
}

function gcd(a: bigint, b: bigint): bigint {
  let x = absBig(a)
  let y = absBig(b)
  while (y !== 0n) {
    const t = x % y
    x = y
    y = t
  }
  return x
}

export function pow10(k: number): bigint {
  if (k < 0) throw new Error('pow10 of a negative power')
  return 10n ** BigInt(k)
}

export function frac(n: bigint, d: bigint = 1n): Frac {
  if (d === 0n) throw new Error('zero denominator')
  if (d < 0n) {
    n = -n
    d = -d
  }
  const g = gcd(n, d)
  return g === 0n || g === 1n ? { n, d } : { n: n / g, d: d / g }
}

/** m x 10^p as a fraction. */
export function fracTimesPow10(m: bigint, p: number): Frac {
  return p >= 0 ? frac(m * pow10(p)) : frac(m, pow10(-p))
}

export const fAdd = (a: Frac, b: Frac): Frac => frac(a.n * b.d + b.n * a.d, a.d * b.d)
export const fSub = (a: Frac, b: Frac): Frac => frac(a.n * b.d - b.n * a.d, a.d * b.d)
export const fMul = (a: Frac, b: Frac): Frac => frac(a.n * b.n, a.d * b.d)
export function fDiv(a: Frac, b: Frac): Frac {
  if (b.n === 0n) throw new Error('division by zero')
  return frac(a.n * b.d, a.d * b.n)
}
export const fEq = (a: Frac, b: Frac): boolean => a.n === b.n && a.d === b.d
export const fIsZero = (a: Frac): boolean => a.n === 0n
export const fAbs = (a: Frac): Frac => ({ n: absBig(a.n), d: a.d })
export const fNeg = (a: Frac): Frac => ({ n: -a.n, d: a.d })

/** floor(log10 |v|): the place of the first significant digit. v must not be zero. */
export function firstPlace(v: Frac): number {
  if (v.n === 0n) throw new Error('zero has no first significant place')
  const n = absBig(v.n)
  const d = v.d
  // ge(k): |v| >= 10^k
  const ge = (k: number): boolean => (k >= 0 ? n >= d * pow10(k) : n * pow10(-k) >= d)
  let k = n.toString().length - d.toString().length
  while (!ge(k)) k--
  while (ge(k + 1)) k++
  return k
}

/** Does the decimal expansion stop? (denominator has no prime factor other than 2 and 5) */
export function terminates(v: Frac): boolean {
  let d = v.d
  while (d % 2n === 0n) d /= 2n
  while (d % 5n === 0n) d /= 5n
  return d === 1n
}

/**
 * Decimal expansion by long division: the integer part, then `fractionDigits` digits produced one
 * remainder at a time. Truncated, never rounded. `exact` says whether nothing was cut off.
 */
export function longDivision(v: Frac, fractionDigits: number): { text: string; exact: boolean } {
  const neg = v.n < 0n
  const n = absBig(v.n)
  let out = (n / v.d).toString()
  let r = n % v.d
  let frac = ''
  for (let i = 0; i < fractionDigits && r !== 0n; i++) {
    r *= 10n
    frac += (r / v.d).toString()
    r %= v.d
  }
  if (frac.length > 0) out += '.' + frac
  return { text: (neg && v.n !== 0n ? '-' : '') + out, exact: r === 0n }
}

/** Minimal plain decimal of a terminating value: "0.0045", "1200", "-3", "0". */
export function plainDecimal(v: Frac): string {
  if (!terminates(v)) throw new Error('plainDecimal of a repeating value')
  const r = longDivision(v, 4000)
  if (!r.exact) throw new Error('expansion too long')
  return r.text
}

// ---------------------------------------------------------------------------
// Reading a numeral
// ---------------------------------------------------------------------------

export interface RefDigit {
  /** Index into the text handed to refParse. */
  index: number
  digit: number
  /** Power of ten this digit stands for (power-of-ten part included). */
  place: number
  significant: boolean
}

export interface RefNumeral {
  ok: true
  value: Frac
  negative: boolean
  isZero: boolean
  sigFigs: number
  /** For zero: same as lastPlace. */
  firstPlace: number
  /** For zero: the place of the last written digit. */
  lastPlace: number
  /** Place of the last WRITTEN coefficient digit, significant or not. */
  lastWrittenPlace: number
  hasPoint: boolean
  scientific: boolean
  /** Scientific with exactly one nonzero digit in front of the point. */
  normalized: boolean
  exponent: number
  digits: RefDigit[]
}

export interface RefParseFailure {
  ok: false
  /** Where the reading stopped (index into the text handed in). */
  position: number
}

const MINUS = '-−'
const isDigit = (c: string | undefined): boolean => c !== undefined && c >= '0' && c <= '9'

/**
 * Grammar (the spec'd student input, nothing more):
 *   [sign] ( digits [ "." [digits] ] | "." digits ) [ power ]
 *   power = ("e" | "E") [sign] digits  |  ("x" | "X" | "×" | "*") "10" "^" [sign] digits     (spaces allowed around
 *           the multiplication sign and the caret)
 * The value is accumulated as integers; nothing is sliced or re-joined.
 */
export function refParse(raw: string): RefNumeral | RefParseFailure {
  let i = 0
  const n = raw.length
  const skipSpaces = (): void => {
    while (i < n && (raw[i] === ' ' || raw[i] === '\t')) i++
  }
  skipSpaces()
  let negative = false
  if (i < n && (raw[i] === '+' || MINUS.includes(raw[i]!))) {
    negative = raw[i] !== '+'
    i++
  }
  let mantissa = 0n
  let digitCount = 0
  let fractionDigits = 0
  let hasPoint = false
  let integerDigits = 0
  const seen: { index: number; digit: number; afterPoint: number }[] = []
  while (i < n) {
    const c = raw[i]!
    if (isDigit(c)) {
      const dv = c.charCodeAt(0) - 48
      mantissa = mantissa * 10n + BigInt(dv)
      digitCount++
      if (hasPoint) fractionDigits++
      else integerDigits++
      seen.push({ index: i, digit: dv, afterPoint: hasPoint ? fractionDigits : 0 })
      i++
    } else if (c === '.' && !hasPoint) {
      hasPoint = true
      i++
    } else break
  }
  if (digitCount === 0) return { ok: false, position: i }

  // optional power of ten
  let exponent = 0
  let scientific = false
  const save = i
  skipSpaces()
  if (i < n) {
    const c = raw[i]!
    let sawPower = false
    if (c === 'e' || c === 'E') {
      i++
      sawPower = true
    } else if (c === 'x' || c === 'X' || c === '×' || c === '*') {
      i++
      skipSpaces()
      if (raw[i] !== '1' || raw[i + 1] !== '0') return { ok: false, position: i }
      i += 2
      skipSpaces()
      if (raw[i] !== '^') return { ok: false, position: i }
      i++
      skipSpaces()
      sawPower = true
    }
    if (sawPower) {
      let eneg = false
      if (i < n && (raw[i] === '+' || MINUS.includes(raw[i]!))) {
        eneg = raw[i] !== '+'
        i++
      }
      if (!isDigit(raw[i])) return { ok: false, position: i }
      let e = 0
      while (isDigit(raw[i])) {
        e = e * 10 + (raw[i]!.charCodeAt(0) - 48)
        if (e > 100000) return { ok: false, position: i }
        i++
      }
      exponent = eneg ? -e : e
      scientific = true
    } else {
      i = save
    }
  }
  skipSpaces()
  if (i < n) return { ok: false, position: i }

  const shift = exponent - fractionDigits // place of the last WRITTEN digit
  const magnitude = fracTimesPow10(mantissa, shift)
  const value = negative ? fNeg(magnitude) : magnitude
  const isZero = mantissa === 0n

  let first: number
  let last: number
  if (isZero) {
    first = shift
    last = shift
  } else {
    first = firstPlace(magnitude)
    if (hasPoint) last = shift
    else {
      let v10 = 0
      let m = mantissa
      while (m % 10n === 0n) {
        m /= 10n
        v10++
      }
      last = shift + v10
    }
  }
  const digits: RefDigit[] = seen.map((s, k) => {
    // k-th written digit of digitCount stands for 10^(shift + digitCount - 1 - k)
    const place = shift + (digitCount - 1 - k)
    return { index: s.index, digit: s.digit, place, significant: !isZero && place <= first && place >= last }
  })
  const normalized = scientific && integerDigits === 1 && seen[0]!.digit !== 0
  return {
    ok: true,
    value,
    negative,
    isZero,
    sigFigs: isZero ? 0 : first - last + 1,
    firstPlace: first,
    lastPlace: last,
    lastWrittenPlace: shift,
    hasPoint,
    scientific,
    normalized,
    exponent,
    digits,
  }
}

export function mustParse(text: string): RefNumeral {
  const p = refParse(text)
  if (!p.ok) throw new Error(`reference cannot read "${text}" (stopped at ${p.position})`)
  return p
}

// ---------------------------------------------------------------------------
// Rounding
// ---------------------------------------------------------------------------

export interface RefRounding {
  value: Frac
  /** Place of the last kept digit (after any carry into a new digit, for figure rounding). */
  place: number
  /** Figures the rounded value shows down to `place`; 0 when it rounded to zero. */
  sigFigs: number
  tie: boolean
  direction: 'up' | 'down' | 'exact'
  firstDropped: number
  truncated: Frac
  /** Place the truncation was made at (no carry can happen when chopping). */
  truncatedPlace: number
  /** Rounding carried into a new leading digit (9.97 -> 10.0). */
  carried: boolean
}

/** Half-up on the magnitude at 10^place, by one integer division with remainder. */
export function refRoundToPlace(v: Frac, place: number): RefRounding {
  const neg = v.n < 0n
  const num = place >= 0 ? absBig(v.n) : absBig(v.n) * pow10(-place)
  const den = place >= 0 ? v.d * pow10(place) : v.d
  const q = num / den
  const r = num % den
  const tie = 2n * r === den
  const up = 2n * r >= den
  const kept = up ? q + 1n : q
  const mk = (m: bigint): Frac => fracTimesPow10(neg ? -m : m, place)
  const value = mk(kept)
  const carried = kept !== 0n && q !== 0n && kept.toString().length !== q.toString().length
  return {
    value,
    place,
    sigFigs: kept === 0n ? 0 : kept.toString().length,
    tie,
    direction: r === 0n ? 'exact' : up ? 'up' : 'down',
    firstDropped: Number((r * 10n) / den),
    truncated: mk(q),
    truncatedPlace: place,
    carried,
  }
}

/** To n significant figures. A carry into a new digit (0.99961 -> 1.00) moves the place up by one. */
export function refRoundToSigFigs(v: Frac, n: number): RefRounding {
  if (fIsZero(v)) throw new Error('cannot round zero to significant figures')
  if (n < 1) throw new Error('need at least one figure')
  const p0 = firstPlace(v)
  const r = refRoundToPlace(v, p0 - n + 1)
  const carried = firstPlace(r.value) !== p0
  return { ...r, place: carried ? r.place + 1 : r.place, sigFigs: n, carried }
}

// ---------------------------------------------------------------------------
// Writing a value so that it SHOWS its last significant place
// ---------------------------------------------------------------------------

export type RefPowerStyle = 'e' | 'E' | 'x10^' | ' x 10^' | '×10^' | ' × 10^' | '*10^' | ' * 10^'

/** Scientific spelling: value is a multiple of 10^place and not zero. */
export function refScientific(v: Frac, place: number, style: RefPowerStyle = 'e', unicodeMinus = false): string {
  if (fIsZero(v)) throw new Error('zero has no scientific form')
  const m = fDiv(fAbs(v), fracTimesPow10(1n, place))
  if (m.d !== 1n) throw new Error('value is not a multiple of 10^place')
  const s = m.n.toString()
  const power = place + s.length - 1
  const minus = unicodeMinus ? '−' : '-'
  const coeff = s.length === 1 ? s : s[0] + '.' + s.slice(1)
  return (v.n < 0n ? minus : '') + coeff + style + (power < 0 ? minus + String(-power) : String(power))
}

/**
 * Standard spelling, or null when plain digits cannot show that place: 2000 good to the hundreds has
 * no standard spelling (its zeros would read as placeholders), 12000 good to the thousands does.
 */
export function refStandard(v: Frac, place: number): string | null {
  const m = fDiv(fAbs(v), fracTimesPow10(1n, place))
  if (m.d !== 1n) throw new Error('value is not a multiple of 10^place')
  let s = m.n.toString()
  const sign = v.n < 0n ? '-' : ''
  if (place > 0) return m.n % 10n === 0n ? null : sign + s + '0'.repeat(place)
  if (place === 0) return sign + s + (s.endsWith('0') && s !== '0' ? '.' : '')
  const f = -place
  while (s.length <= f) s = '0' + s
  return sign + s.slice(0, s.length - f) + '.' + s.slice(s.length - f)
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

export type RefOp = '+' | '-' | '*' | '/'
export interface RefTerm {
  text: string
  exact?: boolean
}
export interface RefGroup {
  terms: RefTerm[]
  ops: RefOp[]
}
export type RefOperand = RefTerm | RefGroup

/** What one operand of a chain brings: its exact value and how far it can be trusted. */
interface Piece {
  value: Frac
  exact: boolean
  /** Meaningful only when !exact. */
  sigFigs: number
  place: number
  /** Figure count / place depends on whether you count before or after rounding (9.97 vs 10.0). */
  debatable: boolean
  /** A measured piece with no significant figure at all (a measured zero, or a group that rounds to zero). */
  degenerate: boolean
}

export interface RefChainResult {
  status: 'ok' | 'unsupported'
  reason?: string
  exactValue: Frac
  terminates: boolean
  rule: 'muldiv' | 'addsub'
  /** muldiv: fewest figures among the measured pieces. */
  limitSigFigs?: number
  /** addsub: least precise place among the measured pieces. */
  limitPlace?: number
  /** Indices (into the chain's pieces) that set the limit. */
  limiting: number[]
  rounding?: RefRounding
  debatable: boolean
}

function termPiece(t: RefTerm): Piece {
  const p = mustParse(t.text)
  return {
    value: p.value,
    exact: t.exact === true,
    sigFigs: p.sigFigs,
    place: p.lastPlace,
    debatable: false,
    degenerate: t.exact !== true && p.isZero,
  }
}

function familyOf(ops: readonly RefOp[]): 'muldiv' | 'addsub' | 'mixed' {
  const md = ops.filter((o) => o === '*' || o === '/').length
  if (md === ops.length) return 'muldiv'
  return md === 0 ? 'addsub' : 'mixed'
}

function fold(pieces: readonly Piece[], ops: readonly RefOp[]): Frac | null {
  let acc = pieces[0]!.value
  for (let k = 0; k < ops.length; k++) {
    const b = pieces[k + 1]!.value
    const op = ops[k]!
    if (op === '/' && fIsZero(b)) return null
    acc = op === '+' ? fAdd(acc, b) : op === '-' ? fSub(acc, b) : op === '*' ? fMul(acc, b) : fDiv(acc, b)
  }
  return acc
}

function chain(pieces: readonly Piece[], ops: readonly RefOp[]): RefChainResult {
  const fam = familyOf(ops)
  const base: RefChainResult = {
    status: 'unsupported',
    exactValue: frac(0n),
    terminates: true,
    rule: fam === 'addsub' ? 'addsub' : 'muldiv',
    limiting: [],
    debatable: pieces.some((p) => !p.exact && p.debatable),
  }
  if (fam === 'mixed') return { ...base, reason: 'ops of both families in one chain' }
  if (ops.length !== pieces.length - 1 || pieces.length < 2) return { ...base, reason: 'shape' }
  const v = fold(pieces, ops)
  if (v === null) return { ...base, reason: 'division by zero' }
  base.exactValue = v
  base.terminates = terminates(v)
  const measured = pieces.map((p, k) => ({ p, k })).filter((x) => !x.p.exact)
  if (measured.length === 0) return { ...base, reason: 'every number is exact' }
  if (measured.some((x) => x.p.degenerate)) return { ...base, reason: 'a measured piece has no significant figures' }
  if (fam === 'muldiv') {
    const nMin = measured.reduce((m, x) => Math.min(m, x.p.sigFigs), Infinity)
    const limiting = measured.filter((x) => x.p.sigFigs === nMin).map((x) => x.k)
    if (fIsZero(v)) return { ...base, reason: 'zero product' }
    return { ...base, status: 'ok', limitSigFigs: nMin, limiting, rounding: refRoundToSigFigs(v, nMin) }
  }
  const pMax = measured.reduce((m, x) => Math.max(m, x.p.place), -Infinity)
  const limiting = measured.filter((x) => x.p.place === pMax).map((x) => x.k)
  return { ...base, status: 'ok', limitPlace: pMax, limiting, rounding: refRoundToPlace(v, pMax) }
}

export function refChain(terms: readonly RefTerm[], ops: readonly RefOp[]): RefChainResult {
  return chain(terms.map(termPiece), ops)
}

export interface RefGroupInfo {
  operandIndex: number
  rule: 'muldiv' | 'addsub'
  exactValue: Frac
  sigFigs: number
  place: number
  debatable: boolean
}

export interface RefMixedResult extends RefChainResult {
  groups: RefGroupInfo[]
}

const isGroup = (o: RefOperand): o is RefGroup => (o as RefGroup).terms !== undefined

/**
 * One level of mixing. A group is evaluated exactly and carried forward with EVERY digit; what it
 * contributes to the outer rule is only "how far it can be trusted":
 *   + - group: its least precise place, and the figures its value shows down to that place;
 *   x / group: its fewest figures, and the place that many figures reach.
 * When counting on the un-rounded value and on the value rounded to that precision give different
 * answers (9.97 good to the tenths: 2 figures, or 10.0: 3 figures) the task is flagged debatable.
 */
export function refMixed(operands: readonly RefOperand[], ops: readonly RefOp[]): RefMixedResult {
  const groups: RefGroupInfo[] = []
  const pieces: Piece[] = []
  let unsupported: string | undefined
  operands.forEach((o, idx) => {
    if (!isGroup(o)) {
      pieces.push(termPiece(o))
      return
    }
    const inner = chain(o.terms.map(termPiece), o.ops)
    if (inner.status !== 'ok' || !inner.rounding) {
      if (inner.reason === 'every number is exact') {
        pieces.push({ value: inner.exactValue, exact: true, sigFigs: 0, place: 0, debatable: false, degenerate: false })
        return
      }
      unsupported = unsupported ?? `group ${idx}: ${inner.reason ?? 'unsupported'}`
      pieces.push({ value: inner.exactValue, exact: false, sigFigs: 0, place: 0, debatable: false, degenerate: true })
      return
    }
    const rounded = inner.rounding
    const v = inner.exactValue
    let sig: number
    let place: number
    let debatable: boolean
    let degenerate = false
    if (inner.rule === 'addsub') {
      place = inner.limitPlace!
      if (fIsZero(rounded.value) || fIsZero(v)) {
        degenerate = true
        sig = 0
        debatable = false
      } else {
        sig = firstPlace(rounded.value) - place + 1
        debatable = firstPlace(v) - place + 1 !== sig
      }
    } else {
      sig = inner.limitSigFigs!
      place = rounded.place
      debatable = rounded.carried
    }
    groups.push({ operandIndex: idx, rule: inner.rule, exactValue: v, sigFigs: sig, place, debatable })
    pieces.push({ value: v, exact: false, sigFigs: sig, place, debatable, degenerate })
  })
  const outer = chain(pieces, ops)
  if (unsupported !== undefined) return { ...outer, status: 'unsupported', reason: unsupported, groups }
  return { ...outer, groups }
}
